---
title: "Notes 1/12/23"
author: "Ev Berger-Wolf"
date: "2023-01-12"
output: html_document
---

#### Markup languages:
- Use specific instructions to explain how a document should look

##### HTML:
- Most common markup language, super straightforward, but uses a lot of characters

##### LaTex:
- Great for document formatting, complex projects, especially in math. Formulas work well.
- Ex: [RSweave document](LaTex_Example.Rnw)

##### Markdown:
- More user-friendly, versatile, etc. Typora is another editor that uses Markdown

##### jekyll themes:
- Requires some html understanding, but a great way to create your own personal website.
- Free jekyll themes [here.](https://jekyllthemes.io/free)

#### Programming in R:
- R started as an S language, but in 1992 became its own language
  - First stable version: 2000
- Advantages:
  - Interactive use
  - Graphics, statistics
  - Active community of coders/contributors
  - Anyone can make packages that are being tested
  - Works on multiple platforms
- Disadvantages:
  - Lazy evaluation
  - Some packages are poorly documented
  - Some functions are hard to learn (steep learning curve)
  - Some packages are unreliable (need to double-check code)
  - Problems with big data (multiple GBs)
[Notes in R](2023-01-12-Scripting-in-R.R)




